spring:
  datasorce:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}5d80bae6a17fdd4dcc922002ab3826763232a049c6d25445a052e715ceba422e'

token:
  expiration_time: 86400000
  secret: user_token_native_user_service_default

gateway:
  ip: 192.168.0.8